### ISSUE TITLE
Any love for Lua?

### ISSUE THREAD

**Issue by gamedevsam** [jakobhellermann/bevy_mod_js_scripting#4]
I think this project is awesome, and a great sign of things to come for the Bevy / Rust game dev ecosystem.

With that said, I think JS/TS as a scripting language is suboptimal due to the complexity of the runtime. Many games use Lua for scripting due to its ease of integration with game engines and generally fast performance.

Have you considered tackling Lua as a scripting language for Bevy?

Might make for a fun project after this one, and possibly reach a "stable" condition much more quickly due to its simplicity.

**Comment by zicklag** [comment]
I think JS/TS is a good solution for scripting because it's very commonly known and taught, and we are able to compile TS without needing tsc, so you get static typing with no need for additional JS toolchains such as npm. And TS type checking comes with VSCode, so it's very low barrier to entry.

Also, using the `deno_core` crate, it's actually very easy to embed V8, which can have quite good performance, too, so complication of embedding hasn't really been troublesome with `deno_core` yet in my experience.

Anyway, Lua _is_ very common in the game development space too, though.

---

I didn't make this project and have barely looked through it so far, but I have been working on something very similar over the last week, and as far as I can figure, it seems that a lot of what's done here can be portable to other scripting languages such as lua.

I'm hoping the dynamic query design can probably be largely re-used and we just have to worry about binding it to another language using whatever Rust bindings or Rust scripting languages we want.

I'm not sure if it's something @jakobhellermann want's to pursue, but either way, I'm hoping that some of the dynamic query interfaces developed here will be able to be ported to other plugins that can use it to implement whatever language they want, after it stabilizes a little bit.

**Comment by jakobhellermann** [comment]
What @zicklag said is pretty much spot on. All the work required for making this crate possible is also required for building language integrations for lua, wasm, LISPs, ...
So far this is just a test bed for building and testing dynamic APIs in bevy.

The next steps would be to extract the language-independant bits like a dynamic query API (#5) etc., and then build specific language integrations for lua, js, etc. (which can be a split community effort).

**Comment by erlend-sh** [comment]
Meanwhile, @makspll is already exploring the Lua angle (with additional `tealr` superpowers, like types and better docs) in https://github.com/makspll/bevy_mod_scripting

For our game we will be trying out both approaches:

- https://github.com/fishfight/punchy/issues/107

**Comment by makspll** [comment]
My crate is very much missing the dynamic query component, but from a quick look it looks like it's possible in current bevy?

**Comment by zicklag** [comment]
> it looks like it's possible in current bevy?

Yep, apparently! I don't understand it all yet, but it's pretty much all self-contained in [`dynamic_query.rs`](https://github.com/jakobhellermann/bevy_mod_js_scripting/blob/main/src/dynamic_query.rs). The workings are a little confusing if you don't know the details about the Bevy ECS ( which I don't yet ), but the code itself is clean and easy to read.

I'm going to try and copy that file to my crate and wire it up to my own script API bindings to see how it works. You could probably do the same with your plugin.

**Comment by makspll** [comment]
Will definitely take inspiration haha, it looks like it'll be very easy to plug it in

**Comment by gamedevsam** [comment]
@erlend-sh thanks for the link, I think that effectively closes out this issue, thanks for the discussion crew!
